title: Lambert Maxime
description: Développeur full stack basé à Rennes, avec plus de 2 ans d’expérience. J’ai travaillé sur l’ensemble du cycle de vie d’applications web — du design d’architecture au déploiement — dans des environnements variés. Je suis actuellement à la recherche d’un nouveau projet où la qualité du produit et l’amélioration continue sont au cœur des priorités.
theme: jekyll-theme-midnight
show_downloads: true
